services:
  backend:
    build: ./backend
    ports: 
      - '8000:8000'
    volumes:
      - ./backend:/usr/src/backend
    # environment:
    #   - DEBUG=True

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/frontend
      - journal:/usr/src/frontend/journal

volumes:
  journal: