# Generated by Django 5.0.6 on 2024-06-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('date_visited', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
