# Generated by Django 5.0.6 on 2024-07-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='date_visited',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
