# Generated by Django 5.0.6 on 2024-07-14 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0002_alter_poi_city_alter_poi_date_visited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='date_visited',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='image',
        ),
    ]
