# Generated by Django 5.0.6 on 2024-07-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0003_remove_poi_date_visited_remove_poi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
