# Generated by Django 5.0.6 on 2024-07-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0004_poi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
